name: carnd-advdl-odlab13
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.7
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scipy
    - ffmpeg
    - imageio
    - pip:
        - moviepy
        - tensorflow-gpu==1.13.1
